// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Iface struct {
	Name  string `json:"name"`
	TxSec string `json:"TX_sec"`
	RxSec string `json:"RX_sec"`
	Tx    string `json:"TX"`
	Rx    string `json:"RX"`
}

type NewIface struct {
	Name  string `json:"name"`
	TxSec string `json:"TX_sec"`
	RxSec string `json:"RX_sec"`
	Tx    string `json:"TX"`
	Rx    string `json:"RX"`
}
