// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NetIFMetrics struct {
	Ifname      string `json:"ifname"`
	RxBytes     uint64 `json:"rxBytes"`
	TxBytes     uint64 `json:"txBytes"`
	RxBytesPSec uint64 `json:"rxBytesPSec"`
	TxBytesPSec uint64 `json:"txBytesPSec"`
}
